#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 24 15:19:15 2017

@author: remnux
"""

import SocketServer
import socket

class EchoHandler(SocketServer.BaseRequestHandler) :
    
    #handle is to be overriden, it is a method of the SocketServer library to 
    #process incoming requests
    def handle(self) :
        
        print "Got connection from : ",self.client_address
        data = 'dummy'
        
        while len(data) :
            data = self.request.recv(1024)
            print "Client sent: " + data
            self.request.send(data)
            
        print "Client left"
            


serverAddr = ("0.0.0.0",9000)

#invoking TCPServer lets your create a TCP server, serverAddr is the 
#address of the server. The second argument is the class that will go ahead
#and handle all the client connecting to this server
server = SocketServer.TCPServer(serverAddr,EchoHandler)

#run the server forever
server.serve_forever()