#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Feb  4 09:39:55 2017

@author: root
"""

import thread
import time
import sys

#Define a function for the thread
def print_time(threadName, delay):
    count = 0
    while count < 5:
        time.sleep(delay)
        count += 1
        print "%s: %s %s" % (threadName, time.ctime(time.time()), count)
        
  
        
# Create two threads as follows
try:
    thread.start_new_thread(print_time,("Thread-1",2,))
    thread.start_new_thread(print_time,("Thread-2",4,))
    
except:
    print "Error: unable to start thread"
    
while True :
    pass

